### ISSUE TITLE
Адаптив страницы homePage

### ISSUE THREAD

**Issue by itgirlschool** [itgirlschool/TatarlarProkoptan#41]
Реализовать адаптив, от 1920 до 375
Сделать адаптивным видео
Подправить текст истории
Добавить правки которые обсуждались в чате
Добавить калаж фотографий

**Comment by MariaLuka** [comment]
![прокопьевск 1](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/42f6aa6d-cf2b-4dec-b1c6-443fe3ca7efd)
![прокопьевск 2](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/e5184aaf-87bb-4d22-a6fd-6c1898252f2b)
![Прокопьевск 3](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/674c5137-59d7-48df-8376-99787be73c35)
![Прокопьевск 4](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/607acb4f-43ed-47d3-80cd-9bc88806e6af)
![Прокопьевск 5](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/fd518587-8dde-41dd-9dcc-ab8b8ff0ed0c)
![Прокопьевск 6](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/b46a6811-1463-4d82-8a7f-1260da79f821)
![прокопьевск 7](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/d1ace62c-f72b-4779-970a-b067ff2d5683)
[](url)
![прокопьевск 8](https://github.com/itgirlschool/TatarlarProkoptan/assets/173056795/c9de7f8b-a320-455b-8f73-a2904e034382)
