### ISSUE TITLE
	 Создать модальное окно для страницы "Благотворительность"

### ISSUE THREAD

**Issue by MariaLuka** [itgirlschool/TatarlarProkoptan#8]
При нажатии “Нажать” появляется форма со сбором данных с графами (фамилия, Имя, отчество, телефон. Предусмотрена возможность согласия со сбором персональных данных. Есть кнопки “Принять участие”( данные уходят на почту заказчицы) и “Отмена”. данные уходят в лк заказчицы

**Comment by NagirnerMark** [comment]
Внизу страницы по центру надпись –«Мы помогаем»
Данный блок не подлежит дальнейшему редактированию   
В качестве фона можно использовать фото                                          	
 При нажатии на блок «Благотворительность» происходит переход на соответствующую страницу.
На этой странице отображается надпись –«Каждый может принять участие в благотворительной помощи и волонтерстве».
Под надписью указан телефон(значок), значки соцсетей ( вк, вотсап) , конверт (почта) для активного  перехода.
«Хочешь присоединиться к команде волонтеров?»(обычная надпись) «Нажать»-пульсирующая надпись
При нажатии “Нажать” появляется форма со сбором данных с графами (фамилия, Имя, отчество, телефон. Предусмотрена возможность согласия со сбором персональных данных. Есть кнопки “Принять участие”( данные уходят на почту заказчицы) и “Отмена”. данные уходят в лк заказчицы
Следующая строка надпись-«Нас много» рядом счетчик с увеличивающимися цифрами (увеличивается при отправке формы , указанной выше)

 
Блок подлежит дальнейшему наполнению и редактированию.
